### ISSUE TITLE
Meth-run

### ISSUE THREAD

**Issue by MeduzieTheGoat** [Project-Sloth/ps-methrun#18]
Hi there man so the meth run works fine but after i kill all the people my third eye does not work on the suitcase so i cannot access it and get the stuff that i need to take back to the first person.

**Comment by LYCoreFramework** [comment]
yah im haveing the same issue

**Comment by Otacon-404** [comment]
cuz hasitem not working as it should in qb-target. 

add this `PlayerData = QBCore.Functions.GetPlayerData()` inside this function `function Functions.HasItem(item)` in qb-target client file

**Comment by KevinGirardx** [comment]
Update your targets
